# 2-8 Finding a Global Maximum With the Sawtooth Method (Shubert-Piyavskii Method)

Here we're finding a global *maximum* instead of the usual minimum. Graphically and conceptually, it's just easier to handle learning this method for maxima rather than minima. It could be adapted, once learned, to finding minima as well, or you could just maximize $–f(x)$. The latter is probably easier.

This section will be light on programming and heavier on paper-and-pencil, though you are encouraged to take shortcuts using small functions, or even write the full program if you like. 

In [1]:
using Interact
using Revealables
include("files/extras.jl")
include("files/answers.jl")

The sawtooth method requires two things that aren't always obvious:

1. Left and right boundaries (from common sense or ceiling methods&mdash;same as previous lesson)
2. A boundary on the slope of the graph...


In [2]:
revealable(slope)

Interact.ToggleButton(1: "input" = false Bool , "Slope Review", false)

  likely near C:\Users\Victoria Docherty\.julia\v0.6\IJulia\src\kernel.jl:31
  likely near C:\Users\Victoria Docherty\.julia\v0.6\IJulia\src\kernel.jl:31
  likely near C:\Users\Victoria Docherty\.julia\v0.6\IJulia\src\kernel.jl:31
  likely near C:\Users\Victoria Docherty\.julia\v0.6\IJulia\src\kernel.jl:31


##Requirements
<img src="files/2-8/redgreenslopes.png" width=200 align="left" />
For the Shubert-Piyavskii method, you need to have a boundary for the slope. 

Both the green and red lines accomplish this&mdash;the curve is not steeper than either one.

With Calculus, you can use derivatives to find a nice boundary slope (the green line). 

Without Calculus, you’ll have to settle for a conservative overestimate (the red line) which could be estimated from data or from a known graph. For now, the boundary slope will be provided. 

##The Sawtooth Method
The Shubert-Piyavskii method, more often called the Sawtooth Method, is a way to find a global maximum on a known interval. Unlike testing points, it is guaranteed to find the global maximum on the interval.

It can be modified to find a global minimum; or you can maximize $(–f(x))$ using the method, which is the same as minimizing $f(x)$.

<img src="files/2-8/intbound.png" width=200 align="left"/>
Step 1: find three points on the function: one at each boundary and one at the midpoint of the interval.

Step 2: using the boundary slope $m$, draw a line through each point with slope $m$ or $–m$. (Note there are two lines through the center point.)


###Practice Problem A
Given the function $y = -x^4 + 4x^3 + 30x^2 – 50x + 200$, boundaries -5 and 7, and a maximum slope of 450...
1. Find the three points (endpoints and midpoint) required by the Sawtooth Method
2. Find the equations of the four lines with slope ±450 through those points. 
3. Find the two points where the left-hand lines cross and the right-hand lines cross.



In [ ]:
# Do calculations here

In [3]:
revealable(hint208A)

Interact.ToggleButton(4: "input-2" = false Bool , "Hints for Easier Calculations", false)

  likely near C:\Users\Victoria Docherty\.julia\v0.6\IJulia\src\kernel.jl:31
  likely near C:\Users\Victoria Docherty\.julia\v0.6\IJulia\src\kernel.jl:31


In [4]:
revealable(ans208A)

Interact.ToggleButton(7: "input-3" = false Bool , "Answer", false)

##Next Steps
Once you have found where the lines cross, you have five points.

Step through the process using the slider. You'll start to see why it's called the Sawtooth Method.


In [5]:
method = [Revealable("The next step is to choose the point with the highest y-value. This point will always be above the function graph if your boundary slope is chosen properly.\n\n<img src=\"files/2-8/crossabovef.png\" width=300 />", "", true), Revealable("Take the x-value of the highest point and plug that into the function to find the actual y-value of the function at that location.\n\n<img src=\"files/2-8/xcoord.png\" width=300 />", "", true), Revealable("Create new lines from the new point. Then find the new crossing points.\n\n<img src=\"files/2-8/newpoints.png\" width=300 />", "", true)]

@manipulate for s = slider(1:3, value=1)
    method[s]
end

Interact.Slider{Int64}(10: "input-4" = 1 Int64 , "", 1, 1:3, "horizontal", true, "d", true)

The next step is to choose the point with the highest y-value. This point will always be above the function graph if your boundary slope is chosen properly.

<img src="files/2-8/crossabovef.png" width=300 />


###Practice Problem B
Given two equations:
* $y - y_1 = m(x - x_1)$
* $y - y_2 = -m(x - x_2)$


1. Write an equation that solves for $y$, given $(x_1, y_1)$ and $(x_2, y_2)$. 
2. Write another equation that solves for $x$, given $y$ in either of the equations above. 
3. Write a program in Julia that finds the crossing point of two lines, given $(x_1, y_1, x_2, y_2)$ and using a constant slope $m$.

   Check your work on Practice Problem A using your program.


In [ ]:
# Code here

In [ ]:
# Test here

In [6]:
revealable(ans208B)

Interact.ToggleButton(14: "input-5" = false Bool , "Answer", false)

###Practice Problem C
Using $y = -x^4 + 4x^3 + 30x^2 – 50x + 200$ with boundary slope 450 and the five current points you have:
1. Choose the point with the highest $y$-value and find the corresponding function $y$-value.
2. Using your program, find where the lines from the new point cross the old lines. 

Now you have seven points. 


In [ ]:
# Find the highest crossing y-value and its corresponding function value


In [ ]:
# Find two new points where the new lines cross old lines


In [7]:
revealable(ans208C)

Interact.ToggleButton(17: "input-6" = false Bool , "Answer", false)

##Next Step: Repeat

In [8]:
@manipulate for s = slider(1:5, value=1)
    steps208[s]
end

Interact.Slider{Int64}(20: "input-7" = 1 Int64 , "", 1, 1:5, "horizontal", true, "d", true)

<img src="files/2-8/step1.png" width=300 />



##Arrays in Julia, revisited
Go back to the original 3 points: $(-5, 75)$, $(1, 183)$, $(7, 291)$. Enter them as an array `A`:

    A = [-5 75; 1 183; 7 291]
    
If we want to add another point into A, we can enter:

    A = vcat(A, [-1.88, 1479])
    
If we want to put the points in order, we can use

    A = sortrows(A)

In [ ]:
# Try it!


##Output of a Function
The command `A = ` in the previous section replaced `A` with the result of the operation. To make sure a function splits out the value of `A` as its final result, you can use the command

    return(A)
    
  or, in Julia,
  
    A
   (or `A =` something)

This command works like `println`, only instead of just printing out the result it will make the result available for assignment to a variable, as in

	y = function(x)

Remember: in Julia, you don't need to write `return`. To return `A` in a function, just make sure `A` is the last line that the function calls.

###Practice Problem D
Write a program `listpoints(A, x, y)` in Julia that adds the point `(x, y)` into array `A`, then sorts the rows. Make sure that you return `A` either with a `return` statement or by making `A` the last thing you evaluate.

Use your program to add in all the points you've found into `A`&mdash;seven total points. Use these statements:
```
A = listpoints([-5, 75], 1, 183)
A = listpoints(A, 7, 291)
A = listpoints(A, -1.88, 1479)
...
println(A)
```

In [9]:
function listpoints(A, x, y) 
    
    
end

listpoints (generic function with 1 method)

In [10]:
A = listpoints([-5, 75], 1, 183)
A = listpoints(A, 7, 291)
A = listpoints(A, -1.88, 1479)
# Add in the other 4 points you've found:

println(A)

nothing


In [11]:
revealable(ans208D)

Interact.ToggleButton(24: "input-8" = false Bool , "Answer", false)

##Repetition Steps
To repeat the process, you would:
1. find the highest $y$-value on your list of points.
2. change that $y$-value to the function value.
3. find the intersection of the lines from this new point to the two adjacent points on the list. 
4. Add both of those points to the list.
Repeat.


###Practice Problem E
Use a combination of your Julia programs:
* a one-line function for the equation $y = -x^4 + 4x^3 + 30x^2 – 50x + 200$
* the program to find intersection points
* and the point-listing program
        
to repeat the sawtooth method at least two more times on the equation. You will finish with at least 11 points in your array.


In [ ]:
# Write your code...

In [ ]:
# and test it

In [12]:
revealable(ans208E)

Interact.ToggleButton(27: "input-9" = false Bool , "Answer", false)

###Extension
Write a program in Julia that, given a function, maximum slope, and endpoints, runs the sawtooth method by either a set number of iterations, or until the highest linear y-value is within 0.01 of the function value. 

One more useful command:

`findmax(A[:, 2])`		
returns the highest y-value and its index (index = number in the array, remember?)

`loc = findmax(A[:, 2])[2]`         
assigns the index with the highest y-value to the variable `loc`.



In [13]:
function sawtooth(f, maxslope, left, right)
    
    
end

sawtooth (generic function with 1 method)

In [ ]:
# Test your code!


In [14]:
revealable(ext208)

Interact.ToggleButton(30: "input-10" = false Bool , "Answer", false)

##If you're curious...

Here are plots of the data after:

5 iterations <img src="files/2-8/5iter.png" width=250 />
<br clear="all" />

10 iterations <img src="files/2-8/10iter.png" width=250 />
<br clear="all" />

15 iterations <img src="files/2-8/15iter.png" width=250 />
<br clear="all" />

20 iterations <img src="files/2-8/20iter.png" width=250 />
<br clear="all" />